version: "3"

services:
  sandbox:
#    image: tqtezos/flextesa:20210602
    image: tqtezos/flextesa:20211206
    environment:
      block_time: 2
      flextesa_node_cors_origin: "*"
    command: /usr/bin/hangzbox start --keep-root
    restart: always

  devenv:
    build:
      context: ./ocaml_tezos_devenv
      dockerfile: ./Dockerfile
      args:
        version: "11.0"
    depends_on: 
      - sandbox
    volumes:
      # Path of the project adjust as needed
      - /home/julian/IdeaProjects/tezos-api/:/root/work/IdeaProjects/tezos-api/
      # additional mounts (here test project and demo contracts) adjust or delete as needed
      - /home/julian/Documents/Studium/Uni/Bachelorprojekt/test_proj/:/root/work/Documents/Studium/Uni/Bachelorprojekt/test_proj/
      - /home/julian/Documents/Studium/Uni/Bachelorprojekt/demo_contracts/:/root/work/Documents/Studium/Uni/Bachelorprojekt/demo_contracts/
    restart: always
