version: "3"

services:
  sandbox:
    image: tqtezos/flextesa:20210602
      #    ports:
      # expose sandbox on localhost if needed
      #      - "127.0.0.1:20000:20000"
    environment:
      block_time: 2
      flextesa_node_cors_origin: "*"
    command: /usr/bin/flobox start --keep-root
    restart: always

  devenv:
    build:
      context: ./ocaml_tezos_devenv
      dockerfile: Dockerfile
      args:
        version: 9.1
    depends_on: 
      - sandbox
    volumes:
      - /home/julian/:/root/work/
    restart: always
